"""add process_document_fields table

Revision ID: 08f4d1830d6e
Revises: ff3680d9390e
Create Date: 2026-05-28 13:52:59.655505

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '08f4d1830d6e'
down_revision: Union[str, None] = 'ff3680d9390e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
