"""add process_extraction_fields table

Revision ID: 7049d8400b12
Revises: 231b178c6ec1
Create Date: 2026-05-26 20:01:28.606395

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7049d8400b12'
down_revision: Union[str, None] = '231b178c6ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_extraction_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_decision', sa.Boolean(), nullable=False),
    sa.Column('null_is_manual', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'name', name='uq_process_field_name')
    )
    op.create_index(op.f('ix_process_extraction_fields_process_id'), 'process_extraction_fields', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_extraction_fields_process_id'), table_name='process_extraction_fields')
    op.drop_table('process_extraction_fields')
    # ### end Alembic commands ###
