"""add process_id to validation_rules

Revision ID: 746ac12a09aa
Revises: 08f4d1830d6e
Create Date: 2026-05-28 18:31:01.726761

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '746ac12a09aa'
down_revision: Union[str, None] = '08f4d1830d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_rules', sa.Column('process_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_validation_rules_process_id'), 'validation_rules', ['process_id'], unique=False)
    op.create_foreign_key(None, 'validation_rules', 'processes', ['process_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_rules', type_='foreignkey')
    op.drop_index(op.f('ix_validation_rules_process_id'), table_name='validation_rules')
    op.drop_column('validation_rules', 'process_id')
    # ### end Alembic commands ###
