"""add process_thresholds table

Revision ID: 826a4e195f01
Revises: 23f46f263bab
Create Date: 2026-05-28 19:46:03.811989

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '826a4e195f01'
down_revision: Union[str, None] = '23f46f263bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_thresholds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=True),
    sa.Column('auto_above', sa.Integer(), nullable=False),
    sa.Column('manual_below', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_thresholds_process_id'), 'process_thresholds', ['process_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_thresholds_process_id'), table_name='process_thresholds')
    op.drop_table('process_thresholds')
    # ### end Alembic commands ###
