"""add process_document_fields table

Revision ID: ff3680d9390e
Revises: 0bb564f45658
Create Date: 2026-05-28 00:18:17.652612

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'ff3680d9390e'
down_revision: Union[str, None] = '0bb564f45658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_document_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_decision', sa.Boolean(), nullable=False),
    sa.Column('null_is_manual', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_document_id'], ['process_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_document_id', 'name', name='uq_process_document_field_name')
    )
    op.create_index(op.f('ix_process_document_fields_process_document_id'), 'process_document_fields', ['process_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_document_fields_process_document_id'), table_name='process_document_fields')
    op.drop_table('process_document_fields')
    # ### end Alembic commands ###
